### ISSUE TITLE
Give more user feedback on check/signat/etc.

### ISSUE THREAD

**Issue by seanvernon** [ocf/utils#125]
It is currently unclear to the user that these commands cannot be used properly outside of supernova. This is made clear if 'usage' is viewed, but if you just enter a command unknowingly you will see a Python error on the command line. I would recommend that we implement a check to change the output and hide the error if the user is not on supernova.

**Comment by ethanhs** [comment]
Yeah I think simply checking the hostname would be best (ie `platform.node()`) and fail if not on supernova.

**Comment by seanvernon** [comment]
Well, some functionality does still work on other machines, what fails is the student org lookup. Perhaps just display a message under the student org section saying “to view this info ssh to supernova”?

**Comment by cg505** [comment]
I use `check` and `checkacct` on other machines all the time: I would like this to continue working. Sean's suggestion is smart I think.

**Comment by ethanhs** [comment]
Yeah I realize I use it on other machines frequently as well. +1 then to using Sean's suggestion.

**Comment by axmmisaka** [comment]
it's a bug that they don't work on other machines - I don't know if it's a bug or feature, but all these information does not require authentication.

See https://github.com/ocf/utils/issues/128

**Comment by jvperrin** [comment]
It's not supposed to be a feature, so this is rightfully a bug. Ideally they should be fixed to work on other machines

**Comment by axmmisaka** [comment]
```
pip3 install ldap3==2.1.1
```
will make everything work. Tried on `hurricane`

**Comment by axmmisaka** [comment]
it can now be properly used i guess
