### ISSUE TITLE
signat weird problem 

### ISSUE THREAD

**Issue by axmmisaka** [ocf/utils#128]
the python error shouldn't happen as the request doesn't require authencate at all (just `curl https://orapps.berkeley.edu/StudentGroupServiceV2/service.asmx/SignatoriesActiveStudentGroups?UID=1234567`).
The problems:
1. supernova is running ldap3 2.1.1 and other machines are running ldap3 1.2.2. lower ldap version caused the respond 'calnetUid' to be a list of strings ['1234567'], but on supernova it's a string ('1234567')
2. supernova is running ocflib june 2019 but normal computers are running ocflib sept2019. 
this pr #171 (51924bf809fbeccc9b0087f78d61b71eda47d49e) screwed up things in some functions in ocflib/account/search.py : 
e.g.
```python3
    calnet_uid = int(calnet_uid)
    return users_by_filter(
        '(calnetUid={})'.format(escape_filter_chars(calnet_uid))
    )
```
`calnet_uid = int(calnet_uid)` actually escaped filter chars, and escape_filter_chars() only takes in str, int or list will all screw it up.

My suggestions:
1. update ldap3 on all machines
2. update ocflib on supernova
3. revert 51924b

**Comment by dkess** [comment]
On supernova I run:
```
$ apt-cache policy python3-ocflib
python3-ocflib:
  Installed: 2019.9.16.14.9~deb9u1
```

So step 2 on your list should be done (I'm not sure how long it's been like this for).

You shouldn't need to revert https://github.com/ocf/ocflib/pull/171, instead you could convert `calnet_uid` to a string before passing it to `escape_filter_chars`.

**Comment by axmmisaka** [comment]
It's sole problem with `ldap3`.
On supernova: 
```
>>> escape_filter_chars(1234556)
'1234556'
>>> ldap3.version.__version__
'2.1.1'
```

On hurricane:
```
>>> ldap3.utils.conv.escape_filter_chars(1234567)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ldap3/utils/conv.py", line 36, in escape_filter_chars
    output = text.replace('\\', r'\5c')
AttributeError: 'int' object has no attribute 'replace'
>>> ldap3.version.__version__
'1.2.2'
```

**Comment by axmmisaka** [comment]
after 
```
pip3 install ldap3==2.1.1
```
`signat` works correctly on `hurricane`
informing #rebuild

**Comment by jvperrin** [comment]
Since we already have `python3-ldap3` packaged and prefer to use system packages where we can (makes it easier to automate out across hosts with puppet, we manage the upgrades already periodically, package structures are more standardized, etc.) then installing the newer version of `python3-ldap3` from our backports on all machines (in https://github.com/ocf/puppet) should fix signat:

```
jvperrin@supernova:~$ apt-cache policy python3-ldap3
python3-ldap3:
  Installed: 2.1.1-1~ocf1
  Candidate: 2.1.1-1~ocf1
  Version table:
 *** 2.1.1-1~ocf1 200
        200 http://apt stretch-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     1.2.2-1 500
        500 http://mirrors/debian stretch/main amd64 Packages
```

**Comment by fydai** [comment]
The python3-ldap3 package can taken from backports instead of the main repositories if a ocf::repackage line is added in puppet here (https://github.com/ocf/puppet/blob/master/modules/ocf/manifests/packages.pp).
