### ISSUE TITLE
Convert python 2 scripts to python 3

### ISSUE THREAD

**Issue by kpengboy** [ocf/utils#19]
There are a few Python 2 scripts left; going with our broader migration to Python 3, we should convert these holdouts over to the current decade.

The specific scripts which aren't slated for removal according to my knowledge are:

```
./acct/chsh
./acct/update-email
./staff/acct/note
./staff/sys/apt-dated
./staff/web/bludgeon
./net/pyrc
```

**Comment by chriskuehl** [comment]
+1

though "rewrite" is probably a bit strong of a word

update-email and chsh might be hard due to not being able to do gssapi for ldap (no python-ldap :()

**Comment by matthew-mcallister** [comment]
We have an [ocflib API](https://github.com/ocf/ocflib/blob/master/ocflib/account/manage.py#L87) for this that works by shelling out to ldapmodify.

There will also be an account settings page in ocfweb in the near future and then no one will have to use update-email or chsh anyways, unless they want to.

**Comment by chriskuehl** [comment]
that won't let you use gssapi though

**Comment by chriskuehl** [comment]
it's not the end of the world, we can just ask people to enter their password again, but it's a kinda sucky regression

ideally we'd figure out how to get that gssapi support in ldap3 to work with our ldap/krb

**Comment by matthew-mcallister** [comment]
Right, of course. At first I thought we could send it to create, but regular users can't submit celery tasks.

**Comment by douglaslwong** [comment]
blockers: chsh, update-email

**Comment by douglaslwong** [comment]
https://github.com/ocf/utils/pull/20 migrated all but chsh and update-email

**Comment by douglaslwong** [comment]
reverting bludgeon for the time being

**Comment by kpengboy** [comment]
bludgeon has been converted to python 3 in #69.

**Comment by jvperrin** [comment]
This is done as of #87!
