### ISSUE TITLE
better awk for ocf-tv

### ISSUE THREAD

**Issue by tahabi** [ocf/utils#40]
#39 needs to have the awk stuff in volume() improved
also it bugs out on 0% due to some spacing issue. Might be useful to forget trying to parse anything and just dump the entire line.

**Comment by chriskuehl** [comment]
reopening to make sure @tahabi's question doesn't get lost:

> Cool. Another issue I noticed is the original version breaks when the volume is 0 because of the way pactl spaces the output. Does this work with volume = 0?

if it does feel free to close again

**Comment by kpengboy** [comment]
That was fixed too
