### ISSUE TITLE
check-dns should handle the no-records case specially

### ISSUE THREAD

**Issue by kpengboy** [ocf/utils#75]
A message like `x_user doesn't have any DNS records associated with them` is more human-friendly than an empty table.

**Comment by abizer** [comment]
`check-dns` is supposed to be used from inside `check`, which sees if there's any output from before printing the "DNS Records for $user" header. If there are no records it should just print nothing, and `check-dns` should return no output, IMO.

**Comment by matthew-mcallister** [comment]
Implemented @abizer's recommendation in https://github.com/ocf/utils/commit/94da5d97799f976bdb0786b08bad9e379599fc56 on grounds that it doesn't require changing `check`. At the moment I don't see any compelling reason to make it behave otherwise.
